# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fpga/Desktop/test/project_final/project_final.srcs/sources_1/bd/design_1/ip/design_1_fourbit_adder_0_0/design_1_fourbit_adder_0_0.xci
# IP: The module: 'design_1_fourbit_adder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fpga/Desktop/test/project_final/project_final.gen/sources_1/bd/design_1/ip/design_1_fourbit_adder_0_0/constraints/fourbit_adder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fourbit_adder_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/fpga/Desktop/test/project_final/project_final.srcs/sources_1/bd/design_1/ip/design_1_fourbit_adder_0_0/design_1_fourbit_adder_0_0.xci
# IP: The module: 'design_1_fourbit_adder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fpga/Desktop/test/project_final/project_final.gen/sources_1/bd/design_1/ip/design_1_fourbit_adder_0_0/constraints/fourbit_adder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fourbit_adder_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
