# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/myxdc.xdc

# Block Designs: bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/design_1/ip/design_1_fourbit_adder_0_0/design_1_fourbit_adder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fourbit_adder_0_0 || ORIG_REF_NAME==design_1_fourbit_adder_0_0} -quiet] -quiet

# XDC: /home/fpga/Desktop/test/project_final/project_final.gen/sources_1/bd/design_1/design_1_ooc.xdc
