set_property SRC_FILE_INFO {cfile:/home/fpga/Desktop/clock_sync/clock_sync.srcs/constrs_1/new/myxdc.xdc rfile:../../../clock_sync.srcs/constrs_1/new/myxdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports led]
